java_test(
    name = "generator-junit4-test",
    srcs = ["GeneratorJunit4Test.java"],
    test_class = "com.xiao.generatorjunit4.GeneratorJunit4Test",
    visibility = ["//src/main/java/com/xiao:__pkg__"],
    deps = [
        "//src/main/java/com/xiao/generator:generator-lib",
        "@maven//:junit_junit",
    ],
)
