load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# JVM related
RULES_JVM_EXTERNAL_TAG = "2.10"
RULES_JVM_EXTERNAL_SHA = "1bbf2e48d07686707dd85357e9a94da775e1dbd7c464272b3664283c9c716d26"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

# Maven dependency
load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    # group : artifact id : version
    artifacts = [

        "com.google.guava:guava:29.0-jre",
#        "com.linecorp.armeria:armeria:1.0.0",
#        "com.linecorp.armeria:armeria-spring-boot2-autoconfigure:1.0.0",
#        "org.springframework.boot:spring-boot:2.3.3.RELEASE",
#        "org.springframework.boot:spring-boot-starter-web:2.3.3.RELEASE",
#        "org.springframework.boot:spring-boot-autoconfigure:2.3.3.RELEASE",

        # Test
        "org.junit.jupiter:junit-jupiter-api:5.6.2",
        "junit:junit:4.13",

        # Test junit5
        "org.junit.jupiter:junit-jupiter-api:5.5.2",
        "org.junit.jupiter:junit-jupiter-engine:5.5.2",
        "org.junit.platform:junit-platform-console:1.5.2"
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://repo1.maven.org/maven2",
    ],
)

