java_library(
    name = "generator-lib",
    srcs = ["Generator.java"],
    visibility = [
        "//src/main/java/com/xiao:__pkg__",
        "//src/test/java/com/xiao/generator:__pkg__",
        "//src/test/java/com/xiao/generatorjunit4:__pkg__"
    ],
    deps = [
        "@maven//:com_google_guava_guava"
    ]
)
